using System.Text;
using System.Text.Json;
using Backend.Models;

namespace Backend.Services;

/// <summary>
/// Generates Unity C# scripts from pipeline processes
/// </summary>
public class CodeGeneratorService
{
    private readonly ILogger<CodeGeneratorService> _logger;

    public CodeGeneratorService(ILogger<CodeGeneratorService> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Generate all scripts for a pipeline
    /// </summary>
    public PipelineScripts GenerateScripts(BuildPipeline pipeline)
    {
        var scripts = new PipelineScripts();

        var preBuildProcesses = pipeline.Processes
            .Where(p => p.IsEnabled && p.Phase == BuildPhase.PreBuild)
            .OrderBy(p => p.Order)
            .ToList();

        var postBuildProcesses = pipeline.Processes
            .Where(p => p.IsEnabled && p.Phase == BuildPhase.PostBuild)
            .OrderBy(p => p.Order)
            .ToList();

        if (preBuildProcesses.Any())
        {
            scripts.PreBuildScript = GeneratePreBuildScript(preBuildProcesses, pipeline.Name);
        }

        if (postBuildProcesses.Any())
        {
            scripts.PostBuildScript = GeneratePostBuildScript(postBuildProcesses, pipeline.Name);
        }

        return scripts;
    }

    private string GeneratePreBuildScript(List<BuildProcess> processes, string pipelineName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Auto-generated by Lumenvil Build System");
        sb.AppendLine("// This file will be deleted after build");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEditor;");
        sb.AppendLine("using UnityEditor.Build;");
        sb.AppendLine("using UnityEditor.Build.Reporting;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine("namespace Lumenvil.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Pipeline: {pipelineName}</summary>");
        sb.AppendLine("    public class LumenvilPreBuild : IPreprocessBuildWithReport");
        sb.AppendLine("    {");
        sb.AppendLine("        public int callbackOrder => -1000;");
        sb.AppendLine();
        sb.AppendLine("        public void OnPreprocessBuild(BuildReport report)");
        sb.AppendLine("        {");
        sb.AppendLine("            Debug.Log(\"[Lumenvil] Running pre-build pipeline...\");");
        sb.AppendLine();

        foreach (var process in processes)
        {
            sb.AppendLine($"            // Process: {process.Name}");
            sb.AppendLine($"            Debug.Log(\"[Lumenvil] Executing: {process.Name}\");");
            sb.Append(GenerateProcessCode(process, "            "));
            sb.AppendLine();
        }

        sb.AppendLine("            Debug.Log(\"[Lumenvil] Pre-build pipeline completed\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private string GeneratePostBuildScript(List<BuildProcess> processes, string pipelineName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Auto-generated by Lumenvil Build System");
        sb.AppendLine("// This file will be deleted after build");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEditor;");
        sb.AppendLine("using UnityEditor.Build;");
        sb.AppendLine("using UnityEditor.Build.Reporting;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine("namespace Lumenvil.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Pipeline: {pipelineName}</summary>");
        sb.AppendLine("    public class LumenvilPostBuild : IPostprocessBuildWithReport");
        sb.AppendLine("    {");
        sb.AppendLine("        public int callbackOrder => 1000;");
        sb.AppendLine();
        sb.AppendLine("        public void OnPostprocessBuild(BuildReport report)");
        sb.AppendLine("        {");
        sb.AppendLine("            Debug.Log(\"[Lumenvil] Running post-build pipeline...\");");
        sb.AppendLine();

        foreach (var process in processes)
        {
            sb.AppendLine($"            // Process: {process.Name}");
            sb.AppendLine($"            Debug.Log(\"[Lumenvil] Executing: {process.Name}\");");
            sb.Append(GenerateProcessCode(process, "            "));
            sb.AppendLine();
        }

        sb.AppendLine("            Debug.Log(\"[Lumenvil] Post-build pipeline completed\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private string GenerateProcessCode(BuildProcess process, string indent)
    {
        var sb = new StringBuilder();

        try
        {
            switch (process.Type)
            {
                case ProcessType.DefineSymbols:
                    sb.Append(GenerateDefineSymbolsCode(process.ConfigurationJson, indent));
                    break;

                case ProcessType.PlayerSettings:
                    sb.Append(GeneratePlayerSettingsCode(process.ConfigurationJson, indent));
                    break;

                case ProcessType.SceneList:
                    sb.Append(GenerateSceneListCode(process.ConfigurationJson, indent));
                    break;

                case ProcessType.CustomCode:
                    sb.Append(GenerateCustomCode(process.ConfigurationJson, indent));
                    break;

                case ProcessType.ShellCommand:
                    sb.Append(GenerateShellCommandCode(process.ConfigurationJson, indent));
                    break;

                case ProcessType.FileCopy:
                    sb.Append(GenerateFileCopyCode(process.ConfigurationJson, indent));
                    break;

                default:
                    sb.AppendLine($"{indent}// Unknown process type: {process.Type}");
                    break;
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to generate code for process {ProcessName}", process.Name);
            sb.AppendLine($"{indent}Debug.LogError(\"[Lumenvil] Failed to execute {process.Name}: Configuration error\");");
        }

        return sb.ToString();
    }

    private string GenerateDefineSymbolsCode(string configJson, string indent)
    {
        var config = JsonSerializer.Deserialize<DefineSymbolsConfig>(configJson) ?? new();
        var sb = new StringBuilder();

        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var targetGroup = EditorUserBuildSettings.selectedBuildTargetGroup;");
        sb.AppendLine($"{indent}    var defines = PlayerSettings.GetScriptingDefineSymbolsForGroup(targetGroup);");
        sb.AppendLine($"{indent}    var defineList = defines.Split(';').Where(d => !string.IsNullOrEmpty(d)).ToList();");

        if (config.Add.Any())
        {
            foreach (var symbol in config.Add)
            {
                sb.AppendLine($"{indent}    if (!defineList.Contains(\"{symbol}\")) defineList.Add(\"{symbol}\");");
            }
        }

        if (config.Remove.Any())
        {
            foreach (var symbol in config.Remove)
            {
                sb.AppendLine($"{indent}    defineList.Remove(\"{symbol}\");");
            }
        }

        sb.AppendLine($"{indent}    PlayerSettings.SetScriptingDefineSymbolsForGroup(targetGroup, string.Join(\";\", defineList));");
        sb.AppendLine($"{indent}    Debug.Log($\"[Lumenvil] Define symbols updated: {{string.Join(\", \", defineList)}}\");");
        sb.AppendLine($"{indent}}}");

        return sb.ToString();
    }

    private string GeneratePlayerSettingsCode(string configJson, string indent)
    {
        var config = JsonSerializer.Deserialize<PlayerSettingsConfig>(configJson) ?? new();
        var sb = new StringBuilder();

        sb.AppendLine($"{indent}{{");

        if (!string.IsNullOrEmpty(config.CompanyName))
            sb.AppendLine($"{indent}    PlayerSettings.companyName = \"{config.CompanyName}\";");

        if (!string.IsNullOrEmpty(config.ProductName))
            sb.AppendLine($"{indent}    PlayerSettings.productName = \"{config.ProductName}\";");

        if (!string.IsNullOrEmpty(config.Version))
            sb.AppendLine($"{indent}    PlayerSettings.bundleVersion = \"{config.Version}\";");

        if (!string.IsNullOrEmpty(config.BundleIdentifier))
            sb.AppendLine($"{indent}    PlayerSettings.applicationIdentifier = \"{config.BundleIdentifier}\";");

        if (config.DefaultScreenWidth.HasValue)
            sb.AppendLine($"{indent}    PlayerSettings.defaultScreenWidth = {config.DefaultScreenWidth};");

        if (config.DefaultScreenHeight.HasValue)
            sb.AppendLine($"{indent}    PlayerSettings.defaultScreenHeight = {config.DefaultScreenHeight};");

        if (config.FullscreenByDefault.HasValue)
            sb.AppendLine($"{indent}    PlayerSettings.fullScreenMode = {(config.FullscreenByDefault.Value ? "FullScreenMode.FullScreenWindow" : "FullScreenMode.Windowed")};");

        if (config.RunInBackground.HasValue)
            sb.AppendLine($"{indent}    PlayerSettings.runInBackground = {config.RunInBackground.Value.ToString().ToLower()};");

        sb.AppendLine($"{indent}    Debug.Log(\"[Lumenvil] PlayerSettings updated\");");
        sb.AppendLine($"{indent}}}");

        return sb.ToString();
    }

    private string GenerateSceneListCode(string configJson, string indent)
    {
        var config = JsonSerializer.Deserialize<SceneListConfig>(configJson) ?? new();
        var sb = new StringBuilder();

        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var scenes = new string[] {{ {string.Join(", ", config.Scenes.Select(s => $"\"{s}\""))} }};");

        if (config.Mode == "include")
        {
            sb.AppendLine($"{indent}    var editorScenes = scenes.Select(s => new EditorBuildSettingsScene(s, true)).ToArray();");
            sb.AppendLine($"{indent}    EditorBuildSettings.scenes = editorScenes;");
        }
        else
        {
            sb.AppendLine($"{indent}    var currentScenes = EditorBuildSettings.scenes.ToList();");
            sb.AppendLine($"{indent}    currentScenes.RemoveAll(s => scenes.Contains(s.path));");
            sb.AppendLine($"{indent}    EditorBuildSettings.scenes = currentScenes.ToArray();");
        }

        sb.AppendLine($"{indent}    Debug.Log($\"[Lumenvil] Scene list updated: {{EditorBuildSettings.scenes.Length}} scenes\");");
        sb.AppendLine($"{indent}}}");

        return sb.ToString();
    }

    private string GenerateCustomCode(string configJson, string indent)
    {
        var config = JsonSerializer.Deserialize<CustomCodeConfig>(configJson) ?? new();
        var sb = new StringBuilder();

        sb.AppendLine($"{indent}try");
        sb.AppendLine($"{indent}{{");

        // Add the custom code with proper indentation
        foreach (var line in config.Code.Split('\n'))
        {
            sb.AppendLine($"{indent}    {line.TrimEnd()}");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}catch (System.Exception ex)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    Debug.LogError($\"[Lumenvil] Custom code error: {{ex.Message}}\");");
        sb.AppendLine($"{indent}}}");

        return sb.ToString();
    }

    private string GenerateShellCommandCode(string configJson, string indent)
    {
        var config = JsonSerializer.Deserialize<ShellCommandConfig>(configJson) ?? new();
        var sb = new StringBuilder();

        var escapedCommand = config.Command.Replace("\\", "\\\\").Replace("\"", "\\\"");

        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var psi = new System.Diagnostics.ProcessStartInfo");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        FileName = Application.platform == RuntimePlatform.WindowsEditor ? \"cmd.exe\" : \"/bin/bash\",");
        sb.AppendLine($"{indent}        Arguments = Application.platform == RuntimePlatform.WindowsEditor ? $\"/c {escapedCommand}\" : $\"-c \\\"{escapedCommand}\\\"\",");
        sb.AppendLine($"{indent}        UseShellExecute = false,");
        sb.AppendLine($"{indent}        RedirectStandardOutput = true,");
        sb.AppendLine($"{indent}        RedirectStandardError = true,");
        sb.AppendLine($"{indent}        CreateNoWindow = true");
        sb.AppendLine($"{indent}    }};");

        if (!string.IsNullOrEmpty(config.WorkingDirectory))
        {
            sb.AppendLine($"{indent}    psi.WorkingDirectory = \"{config.WorkingDirectory.Replace("\\", "\\\\")}\";");
        }

        sb.AppendLine($"{indent}    var process = System.Diagnostics.Process.Start(psi);");
        sb.AppendLine($"{indent}    process.WaitForExit({config.TimeoutSeconds * 1000});");
        sb.AppendLine($"{indent}    var output = process.StandardOutput.ReadToEnd();");
        sb.AppendLine($"{indent}    var error = process.StandardError.ReadToEnd();");
        sb.AppendLine($"{indent}    if (!string.IsNullOrEmpty(output)) Debug.Log($\"[Lumenvil] Shell output: {{output}}\");");
        sb.AppendLine($"{indent}    if (!string.IsNullOrEmpty(error)) Debug.LogWarning($\"[Lumenvil] Shell error: {{error}}\");");
        sb.AppendLine($"{indent}}}");

        return sb.ToString();
    }

    private string GenerateFileCopyCode(string configJson, string indent)
    {
        var config = JsonSerializer.Deserialize<FileCopyConfig>(configJson) ?? new();
        var sb = new StringBuilder();

        var escapedSource = config.Source.Replace("\\", "\\\\");
        var escapedDest = config.Destination.Replace("\\", "\\\\");

        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var source = \"{escapedSource}\";");
        sb.AppendLine($"{indent}    var dest = \"{escapedDest}\";");
        sb.AppendLine($"{indent}    var searchOption = {(config.Recursive ? "System.IO.SearchOption.AllDirectories" : "System.IO.SearchOption.TopDirectoryOnly")};");
        sb.AppendLine($"{indent}    ");
        sb.AppendLine($"{indent}    if (System.IO.Directory.Exists(source))");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        System.IO.Directory.CreateDirectory(dest);");
        sb.AppendLine($"{indent}        foreach (var file in System.IO.Directory.GetFiles(source, \"{config.Pattern}\", searchOption))");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            var relativePath = file.Substring(source.Length).TrimStart('\\\\', '/');");
        sb.AppendLine($"{indent}            var destPath = System.IO.Path.Combine(dest, relativePath);");
        sb.AppendLine($"{indent}            System.IO.Directory.CreateDirectory(System.IO.Path.GetDirectoryName(destPath));");
        sb.AppendLine($"{indent}            System.IO.File.Copy(file, destPath, {config.Overwrite.ToString().ToLower()});");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}        Debug.Log($\"[Lumenvil] Files copied from {{source}} to {{dest}}\");");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}    else");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        Debug.LogWarning($\"[Lumenvil] Source directory not found: {{source}}\");");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");

        return sb.ToString();
    }
}

/// <summary>
/// Generated scripts for a pipeline
/// </summary>
public class PipelineScripts
{
    public string? PreBuildScript { get; set; }
    public string? PostBuildScript { get; set; }

    public bool HasScripts => !string.IsNullOrEmpty(PreBuildScript) || !string.IsNullOrEmpty(PostBuildScript);
}
